### ISSUE TITLE
RFE - specify the commit to use when running components e2e tests

### ISSUE THREAD

**Issue by maiqueb** [kubevirt/cluster-network-addons-operator#1548]
**What happened**:
The components e2e tests are executed using the version of the tests pointed to by `components.yaml`.

If a bug is found on a component's tests, it's maintainer must patch the e2e test code, then release a new version (makes no sense, since there's no production code changes IMO), and finally patch CNAO.

**What you expected to happen**:
Have a way to override a component's e2e test commit.

**Comment by oshoval** [comment]
currently cnao is flaky because we need https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/pull/141

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1573/pull-e2e-cnao-multus-dynamic-networks-functests/1676239285327499264

all the components at cnao are tagged, and it is better imho this way,
it is predictable and maintainable this way

few suggestions:
1. if possible please release a version on multus-dynamic-networks-controller
2. we can change components.yaml to be static, and then use a hash

wdyt ?
/cc @RamLavi @qinqon

**Comment by phoracek** [comment]
WRT the failing lane. We cannot control when upstream tags a new release. However, there is no point in running a broken e2e lane that only adds noise to our PRs. I suggest we disable that lane until a new release of the controller is released @oshoval

**Comment by oshoval** [comment]
Tried to see if the tests fix solves all the flakes, it improves a bit from what i saw in the past, but doesn't solve all
https://github.com/kubevirt/cluster-network-addons-operator/pull/1586

so created this PR according the discussion above, see please https://github.com/kubevirt/project-infra/pull/2884

**Comment by RamLavi** [comment]
The stale label made me re-read the issue. 
IMO There's no need to have a add infrastructure to it. 
@maiqueb - how about this WA: pushing a draft PR, where you also tell the e2e specifically from what commit to fetch the component instead of it taking from the components file(see [here](https://github.com/kubevirt/cluster-network-addons-operator/blob/main/automation/components-functests.setup.sh#L80)):

```
git-utils::fetch_component ${component_path} ${component_url} <your-hard-coded-commit-just-to-check-on-the-pr>
```

**Comment by oshoval** [comment]
created https://issues.redhat.com/browse/CNV-46276
